import type { Template } from '../types/browse-templates';

export const templates: Template[] = [
  {
    id: 1,
    title: "Hack The Future",
    type: "Hackathon",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-1.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#E2E7D5",
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-2.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#F0F0E8",
  },
  {
    id: 7,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-7.png",
    tag: "Trending",
    bg: "#B1F4E7",
  },
  {
    id: 5,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-5.png",
    tag: null,
    bg: "#FFEDDD",
  },
];
