import { Template } from "../types/explore";

export const STATS = [
	{ value: "1,240", label: "Templates" },
	{ value: "48k", label: "Badges Made" },
	{ value: "3.2k", label: "Organizers" },
];

export const FILTERS = [
	"All",
	"Conference",
	"Hackathon",
	"Community",
	"Trending",
];

export const templates: Template[] = [
	{
		id: 1,
		title: "Hack The Future",
		type: "Hackathon",
		creator: "@techevents",
		location: "Lagos",
		badgeCount: "330",
		image: "/assets/landing-page/template1.svg",
		tag: "Trending",
		hasShadow: true,
	},
	// {
	// 	id: 2,
	// 	title: "Dev Summit '26",
	// 	type: "Conference",
	// 	creator: "@techevents",
	// 	location: "Abuja",
	// 	badgeCount: "42",
	// 	image: "/assets/landing-page/template2.svg",
	// 	tag: "Trending",
	// 	hasShadow: true,
	// },
	{
		id: 3,
		title: "Connect Meetup",
		type: "Conference",
		creator: "@techevents",
		location: "Berlin",
		badgeCount: "1,001",
		image: "/assets/landing-page/template3.svg",
		tag: "New",
	},
	{
		id: 4,
		title: "Cyber Fest",
		type: "Conference",
		creator: "@techevents",
		location: "Port Harcourt",
		badgeCount: "3",
		image: "/assets/landing-page/template4.svg",
		tag: null,
		hasShadow: true,
	},
	// {
	//   id: 6,
	//   title: "Vedo",
	//   type: 'Community',
	//   creator: '@techevents',
	//   location: 'Abuja',
	//   badgeCount: '652',
	//   image: '/assets/landing-page/template6.svg',
	//   tag: null,
	// },
	{
		id: 7,
		title: "Stingy Men '26",
		type: "Conference",
		creator: "@stingymenconf",
		location: "Lagos",
		badgeCount: "90",
		image: "/assets/landing-page/template7.svg",
		tag: "Trending",
	},
	// {
	// 	id: 8,
	// 	title: "Sabi Girls SQ",
	// 	type: "Community",
	// 	creator: "@sabigirls.sq",
	// 	location: "Lagos",
	// 	badgeCount: "999",
	// 	image: "/assets/landing-page/template8.svg",
	// 	tag: null,
	// },
];
