import { Template } from '../types/explore';

export const STATS = [
  { value: '1,240', label: 'Templates' },
  { value: '48k', label: 'Badges Made' },
  { value: '3.2k', label: 'Organizers' },
];

export const FILTERS = [
  'All',
  'Conference',
  'Hackathon',
  'Community',
  'Bootcamp',
  'Meetup',
  'Speaker',
  'Trending',
];

export const templates: Template[] = [
  {
    id: 1,
    title: 'Hack The Future',
    type: 'Hackathon',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-1.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-2.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 3,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-3.png',
    tag: 'New',
  },
  {
    id: 4,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-4.png',
    tag: null,
    hasShadow: true,
  },
  {
    id: 5,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-5.png',
    tag: null,
  },
  {
    id: 6,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-6.png',
    tag: null,
  },
  {
    id: 7,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-7.png',
    tag: 'Trending',
  },
  {
    id: 8,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-8.png',
    tag: null,
  },
  {
    id: 9,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-9.png',
    tag: null,
  },
  {
    id: 10,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-10.png',
    tag: null,
  },
  {
    id: 11,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-11.png',
    tag: null,
  },
  {
    id: 12,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-12.png',
    tag: null,
  },
];
