import { Template } from '../types/explore';

export const STATS = [
  { value: '1,240', label: 'Templates' },
  { value: '48k', label: 'Badges Made' },
  { value: '3.2k', label: 'Organizers' },
];

export const FILTERS = [
  'All',
  'Conference',
  'Hackathon',
  'Community',
  'Trending',
];

export const templates: Template[] = [
  {
    id: 1,
    title: 'Hack The Future',
    type: 'Hackathon',
    creator: '@hackathon_lagos',
    location: 'Lagos',
    badgeCount: '330',
    image: '/assets/landing-page/template-1.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@abj.techevents',
    location: 'Abuja',
    badgeCount: '42',
    image: '/assets/landing-page/template-2.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 3,
    title: "Connect Meetup",
    type: 'Conference',
    creator: '@global_techevents',
    location: 'Berlin',
    badgeCount: '1,001',
    image: '/assets/landing-page/template-3.png',
    tag: 'New',
  },
  {
    id: 4,
    title: "Cyber Fest",
    type: 'Conference',
    creator: '@cyber_conf',
    location: 'Port Harcourt',
    badgeCount: '3',
    image: '/assets/landing-page/template-4.png',
    tag: null,
    hasShadow: true,
  },
  {
    id: 5,
    title: "WAI '26",
    type: 'Conference',
    creator: '@wai.techevents',
    location: 'Lagos',
    badgeCount: '564',
    image: '/assets/landing-page/template-5.png',
    tag: null,
  },
  {
    id: 6,
    title: "Vedo",
    type: 'Community',
    creator: '@vedo_abuja',
    location: 'Abuja',
    badgeCount: '652',
    image: '/assets/landing-page/template-6.png',
    tag: null,
  },
  {
    id: 7,
    title: "Stingy Men '26",
    type: 'Conference',
    creator: '@stingymenconf',
    location: 'Lagos',
    badgeCount: '90',
    image: '/assets/landing-page/template-7.png',
    tag: 'Trending',
  },
  {
    id: 8,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls.sq',
    location: 'Lagos',
    badgeCount: '999',
    image: '/assets/landing-page/template-8.png',
    tag: null,
  },
  {
    id: 9,
    title: 'Next Gen Meetup',
    type: 'Conference',
    creator: '@next_gen_ng',
    location: 'Lagos',
    badgeCount: '14',
    image: '/assets/landing-page/template-9.png',
    tag: null,
  },
  {
    id: 10,
    title: 'Achiever Summit',
    type: 'Community',
    creator: '@achieverzzz',
    location: 'Lagos',
    badgeCount: '78',
    image: '/assets/landing-page/template-10.png',
    tag: null,
  },
  {
    id: 11,
    title: 'Akungba',
    type: 'Community',
    creator: '@akungba_life',
    location: 'Abuja',
    badgeCount: '38',
    image: '/assets/landing-page/template-11.png',
    tag: null,
  },
  {
    id: 12,
    title: 'Soft Life HQ',
    type: 'Community',
    creator: '@softlifehq',
    location: 'Lagos',
    badgeCount: '200',
    image: '/assets/landing-page/template-12.png',
    tag: null,
  },
];
