import { Template } from "../types/template";

export const templates: Template[] = [
  {
    id: 1,
    title: "Lagos Street",
    type: "Festival",
    creator: "@lagoscarnival",
    location: "Lagos",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-13.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#F6EDE5",
  },
  {
    id: 2,
    title: "London Festival",
    type: "Festival",
    creator: "@londoncarnival",
    location: "London",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-14.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#F6EDE5",
  },
  {
    id: 3,
    title: "China Festival",
    type: "Festival",
    creator: "@streetfoodz",
    location: "China",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-15.png",
    tag: "New",
    bg: "#F6EDE5",
  },
  {
    id: 4,
    title: "Carnival Party",
    type: "Festival",
    creator: "@techevents",
    location: "New Orleans",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-16.png",
    tag: null,
    hasShadow: true,
    bg: "#F6EDE5",
  },
  // {
  //   id: 5,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-5.png",
  //   tag: null,
  //   bg: "#ECE3F7",
  // },
  // {
  //   id: 6,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-6.png",
  //   tag: null,
  // },
  // {
  //   id: 7,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-7.png",
  //   tag: "Trending",
  //   bg: "#DFF2E9",
  // },
  // {
  //   id: 8,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-8.png",
  //   tag: null,
  // },
  // {
  //   id: 9,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-9.png",
  //   tag: null,
  // },
  // {
  //   id: 10,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-10.png",
  //   tag: null,
  // },
  // {
  //   id: 11,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-11.png",
  //   tag: null,
  // },
  // {
  //   id: 12,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-12.png",
  //   tag: null,
  // },
];
