import { Template } from "../types/template";

export const templates: Template[] = [
  {
    id: 1,
    title: "Hack The Future",
    type: "Hackathon",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-1.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#F3F1EA",
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-2.png",
    tag: "Trending",
    hasShadow: true,
    bg: "#EEEDE5",
  },
  // {
  //   id: 3,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-3.png",
  //   tag: "New",
  // },
  // {
  //   id: 4,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-4.png",
  //   tag: null,
  //   hasShadow: true,
  // },
  {
    id: 5,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-5.png",
    tag: null,
    bg: "#ECE3F7",
  },
  // {
  //   id: 6,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-6.png",
  //   tag: null,
  // },
  {
    id: 7,
    title: "Dev Summit '26",
    type: "Conference",
    creator: "@techevents",
    location: "Berlin",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-7.png",
    tag: "Trending",
    bg: "#DFF2E9",
  },
  // {
  //   id: 8,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-8.png",
  //   tag: null,
  // },
  // {
  //   id: 9,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-9.png",
  //   tag: null,
  // },
  // {
  //   id: 10,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-10.png",
  //   tag: null,
  // },
  // {
  //   id: 11,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-11.png",
  //   tag: null,
  // },
  // {
  //   id: 12,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-12.png",
  //   tag: null,
  // },
];
