import { Template } from "../types/templates/template";

export const templates: Template[] = [
  {
    id: 1,
    title: "Achiever",
    type: "Conferences",
    creator: "@techevents",
    location: "Lagos",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-10.png",
    tag: "Trending",
    hasShadow: false,
    bg: "linear-gradient(rgb(255,240,244), rgb(255,228,218))",
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: "Conferences",
    creator: "@techevents",
    location: "Abuja",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-2.png",
    tag: "Trending",
    hasShadow: true,
    bg: "linear-gradient(rgb(180,180,180), rgb(241,239,232))",
  },
  {
    id: 3,
    title: "Men's Summit",
    type: "Conferences",
    creator: "@techevents",
    location: "Port Harcourt",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-17.png",
    tag: "New",
    bg: "linear-gradient(rgb(202, 200, 204), rgb(202, 197, 209))",
  },
  {
    id: 4,
    title: "Next Gen Meetup",
    type: "Conferences",
    creator: "@techevents",
    location: "Lagos",
    badgeCount: "4,230",
    image: "/assets/landing-page/template-9.png",
    tag: null,
    hasShadow: true,
    bg: "linear-gradient(rgb(231, 255, 235), rgb(138, 181, 144))",
  },
  // {
  //   id: 5,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-5.png",
  //   tag: null,
  //   bg: "#ECE3F7",
  // },
  // {
  //   id: 6,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-6.png",
  //   tag: null,
  // },
  // {
  //   id: 7,
  //   title: "Dev Summit '26",
  //   type: "Conference",
  //   creator: "@techevents",
  //   location: "Berlin",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-7.png",
  //   tag: "Trending",
  //   bg: "#DFF2E9",
  // },
  // {
  //   id: 8,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-8.png",
  //   tag: null,
  // },
  // {
  //   id: 9,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-9.png",
  //   tag: null,
  // },
  // {
  //   id: 10,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-10.png",
  //   tag: null,
  // },
  // {
  //   id: 11,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-11.png",
  //   tag: null,
  // },
  // {
  //   id: 12,
  //   title: "Sabi Girls SQ",
  //   type: "Community",
  //   creator: "@sabigirls",
  //   location: "Lagos",
  //   badgeCount: "4,230",
  //   image: "/assets/landing-page/template-12.png",
  //   tag: null,
  // },
];
