import type { CustomizeEditorState } from "../types/canvas-data";

export const PREVIEW_LAYOUTS: Record<string, CustomizeEditorState> = {
	circle_photo_dark_v1: {
		platformTemplateId: "circle_photo_dark_v1",
		layoutId: "circle_photo_dark_v1",
		title: "Dark Circle",
		eventName: "DESIGNWEEKLAGOS",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Designer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1e1e1e", "#1e1e1e"],
		gradientDirection: "135deg",
		solidColor: "#1e1e1e",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	bold_name_pink_v1: {
		platformTemplateId: "bold_name_pink_v1",
		layoutId: "bold_name_pink_v1",
		title: "Design Week Pink",
		eventName: "#DesignWeekLagos",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Designer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_pink",
		gradientColors: ["#f5c6d0", "#f5c6d0"],
		gradientDirection: "135deg",
		solidColor: "#f5c6d0",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	hng_finalist_v1: {
		platformTemplateId: "hng_finalist_v1",
		layoutId: "hng_finalist_v1",
		title: "HNG Finalist",
		eventName: "HNG FINALIST",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Designer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1a1a1a", "#1a1a1a"],
		gradientDirection: "135deg",
		solidColor: "#1a1a1a",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	hng_finalist_dev_v1: {
		platformTemplateId: "hng_finalist_dev_v1",
		layoutId: "hng_finalist_dev_v1",
		title: "HNG Developer",
		eventName: "HNG FINALIST",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Software Engineer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1a1a1a", "#1a1a1a"],
		gradientDirection: "135deg",
		solidColor: "#1a1a1a",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	hng_finalist_design_v1: {
		platformTemplateId: "hng_finalist_design_v1",
		layoutId: "hng_finalist_design_v1",
		title: "HNG Designer",
		eventName: "HNG FINALIST",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Designer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1a1a1a", "#1a1a1a"],
		gradientDirection: "135deg",
		solidColor: "#1a1a1a",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	hng_finalist_pm_v1: {
		platformTemplateId: "hng_finalist_pm_v1",
		layoutId: "hng_finalist_pm_v1",
		title: "HNG PM",
		eventName: "HNG FINALIST",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Manager",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1a1a1a", "#1a1a1a"],
		gradientDirection: "135deg",
		solidColor: "#1a1a1a",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
	hng_finalist_flaretag_v1: {
		platformTemplateId: "hng_finalist_flaretag_v1",
		layoutId: "hng_finalist_flaretag_v1",
		title: "HNG Flaretag",
		eventName: "HNG FINALIST",
		eventDate: "",
		eventTime: "",
		participantNameLabel: "NAME",
		participantNamePlaceholder: "Sandra Robinson",
		roleTitleLabel: "ROLE / TITLE",
		roleTitlePlaceholder: "Product Designer",
		roleTitleRequired: false,
		allowParticipantPhoto: true,
		logo: null,
		logoPreviewUrl: null,
		pendingLogoFile: null,
		bgMode: "solid",
		paletteId: "bg_color_dark",
		gradientColors: ["#1a1a1a", "#1a1a1a"],
		gradientDirection: "135deg",
		solidColor: "#1a1a1a",
		backgroundImageUrl: null,
		fontId: "inter",
		titleSize: "MEDIUM",
		defaultCaption: "",
		hashtags: [],
		accessType: 0,
		participantNameVisible: true,
		roleTitleVisible: true,
	},
};
