export const templates = [
  {
    id: 1,
    title: 'Hack The Future',
    type: 'Hackathon',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-1.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 2,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-2.png',
    tag: 'Trending',
    hasShadow: true,
  },
  {
    id: 3,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-3.png',
    tag: 'New',
  },
  {
    id: 4,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-4.png',
    tag: null,
    hasShadow: true,
  },
  {
    id: 5,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-5.png',
    tag: null,
  },
  {
    id: 6,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-6.png',
    tag: null,
  },
  {
    id: 7,
    title: "Dev Summit '26",
    type: 'Conference',
    creator: '@techevents',
    location: 'Berlin',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-7.png',
    tag: 'Trending',
  },
  {
    id: 8,
    title: 'Sabi Girls SQ',
    type: 'Community',
    creator: '@sabigirls',
    location: 'Lagos',
    badgeCount: '4,230',
    image: '/assets/landing-page/template-8.png',
    tag: null,
  },
];
